name: Language Activity
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
              filename: metrics.plugin.languages.recent.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_languages: yes
              plugin_languages_ignored: >-
                html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
                gnuplot
              plugin_languages_sections: recently-used
              plugin_languages_details: bytes-size, percentage
              plugin_languages_limit: 5
      - uses: lowlighter/metrics@latest
        with:
              filename: metrics.plugin.languages.svg
              token: ${{ secrets.METRICS_TOKEN }}
              base: ""
              plugin_languages: yes
              plugin_languages_ignored: >-
                html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
                gnuplot
              plugin_languages_limit: 5
    
